// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH2lt75NOzilM52cycgQv48dGY4rDVRy0',
    appId: '1:211826518707:web:6a57a23a609d3cc21e9ec6',
    messagingSenderId: '211826518707',
    projectId: 'wide-office-315415',
    authDomain: 'wide-office-315415.firebaseapp.com',
    storageBucket: 'wide-office-315415.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy0i3WxWl9C-biASxFMouz9ANV3Cx6j6w',
    appId: '1:211826518707:android:c31cf8588281a39f1e9ec6',
    messagingSenderId: '211826518707',
    projectId: 'wide-office-315415',
    storageBucket: 'wide-office-315415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9SDEFv2nLTpeedGi7wWjhcf3Cq57CBLY',
    appId: '1:211826518707:ios:45f0a5251e011d701e9ec6',
    messagingSenderId: '211826518707',
    projectId: 'wide-office-315415',
    storageBucket: 'wide-office-315415.appspot.com',
    iosClientId: '211826518707-8knh5jet5p90l2k505mh28mhoth8gcvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.renandashtcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9SDEFv2nLTpeedGi7wWjhcf3Cq57CBLY',
    appId: '1:211826518707:ios:e3079c2de77566591e9ec6',
    messagingSenderId: '211826518707',
    projectId: 'wide-office-315415',
    storageBucket: 'wide-office-315415.appspot.com',
    iosClientId: '211826518707-ikc2kqo87tmbhe1h2ha4ugtrgrsaj67n.apps.googleusercontent.com',
    iosBundleId: 'com.example.renandashtcc.RunnerTests',
  );
}
